[project]
name = "niall2"
version = "0.0.0"
dependencies = [
    "boto3",
]

[project.optional-dependencies]
dev = [
    "pytest",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
